# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z4JenCpXDaq__uUlMqhTltcgHPvIQ5H9
"""

from google.colab import files
from PIL import Image
import matplotlib.pyplot as plt

# بارگذاری تصویر از کاربر
uploaded = files.upload()

# فرض بر این است که کاربر فقط یک تصویر آپلود کرده است
input_image_path = list(uploaded.keys())[0]
input_image = Image.open(input_image_path)

# اطمینان از اینکه اندازه تصویر 900x900 باشد
if input_image.size != (900, 900):
 print("تصویر ورودی باید 900x900 پیکسل باشد.")
 exit()

# 9 تصویر 100x100 خالی ایجاد می‌کنیم
output_images = []
for i in range(9):
 img = Image.new('RGB', (100, 100), color='white') # پس‌زمینه سفید
 output_images.append(img)

# تقسیم تصویر 900x900 به 9 بخش 100x100
for i in range(3):
 for j in range(3):
 # محاسبه مختصات هر بخش 100x100
  left = j * 100
  top = i * 100
  right = left + 100
  bottom = top + 100
  # برش هر بخش از تصویر اصلی
  cropped_image = input_image.crop((left, top, right, bottom))

 # قرار دادن بخش در تصویر مربوطه
  output_images[i * 3 + j].paste(cropped_image, (0, 0))

# نمایش تصاویر
fig, axs = plt.subplots(3, 4, figsize=(12, 8))

# نمایش تصویر اصلی
axs[0, 0].imshow(input_image)
axs[0, 0].set_title("Original Image (900x900)")
axs[0, 0].axis('off')

# نمایش تصاویر 100x100
for i in range(9):
  row = (i // 3) + 1
  col = i % 3
  axs[row, col].imshow(output_images[i])
  axs[row, col].set_title(f"Image {i + 1} (100x100)")
  axs[row, col].axis('off')

plt.tight_layout()
plt.show()